# ---- STAGE 1: Builder ----
# Use the full Node.js 22 Alpine image. Alpine is smaller than the default Debian.
FROM node:22-alpine AS builder

# Set the working directory inside the container.
WORKDIR /app

# Copy package.json and package-lock.json first.
# This leverages Docker's layer caching.
COPY package*.json ./

# Use 'npm ci' which is faster and more reliable for CI/CD environments.
RUN npm ci
RUN npm audit --omit=dev --audit-level=high

# Copy the rest of the application source code into the container.
# THIS COPIES THE .env FILE GENERATED BY CLOUD BUILD!
# By leveraging the workspace .env, we eliminate all ARG and ENV boilerplates.
COPY . .

# Run the Nuxt build command. 
# Nuxt natively processes the .env file during this build step to bake in NUXT_PUBLIC_* variables.
RUN NODE_OPTIONS="--max-old-space-size=4096" npm run build


# ---- STAGE 2: Runner ----
# Start from a fresh, minimal Node.js Alpine image for the final production container.
FROM node:22-alpine

# Set the working directory for the running application.
WORKDIR /app

# Set ownership of the working directory to the built-in 'node' user
RUN chown -R node:node /app

# Switch to the non-root user to resolve SCA root execution warnings.
USER node

# Nuxt 3's build output is a self-contained '.output' directory.
# We ONLY need to copy this single directory from our 'builder' stage.
# We also ensure the 'node' user owns this copied directory.
COPY --chown=node:node --from=builder /app/.output ./.output

# Add a healthcheck to resolve SAST 'No HEALTHCHECK defined' warnings
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
  CMD node -e "fetch('http://localhost:3000/').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"

# Expose the port the Nuxt server will listen on.
# Cloud Run will route external traffic to this port.
EXPOSE 3000

# Set HOST to 0.0.0.0 so it binds to all interfaces, which is required by Cloud Run.
ENV HOST=0.0.0.0
ENV PORT=3000

# The command to start the Nuxt server.
# It checks if the Cloud Run secret is mounted at /etc/secrets/.env and loads it via node --env-file.
CMD ["sh", "-c", "if [ -f /etc/secrets/.env ]; then node --env-file=/etc/secrets/.env .output/server/index.mjs; else node .output/server/index.mjs; fi"]

